import { ReactNode } from "react";
import type { Metadata } from "next";
import { Experimental_CssVarsProvider as CssVarsProvider } from "@mui/material/styles";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import { mainTheme } from "@/themes";
import StoreProvider from "@/app/StoreProvider";
import AlertToast from "@/components/AlertToast";
import TokenRefresher from "@/app/TokenRefresher";

export const metadata: Metadata = {
  title: "Compartytion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko">
      <body style={{ margin: 0 }}>
        <StoreProvider>
          <TokenRefresher>
            <AppRouterCacheProvider>
              <CssVarsProvider theme={mainTheme}>
                {children}
                <AlertToast />
              </CssVarsProvider>
            </AppRouterCacheProvider>
          </TokenRefresher>
        </StoreProvider>
      </body>
    </html>
  );
}
