import { ReactNode } from "react";
import type { Metadata } from "next";

import { AppBar, Toolbar } from "@mui/material";
import { Experimental_CssVarsProvider as CssVarsProvider } from "@mui/material/styles";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import theme from "@/theme";
import Typography from "@mui/material/Typography";

export const metadata: Metadata = {
  title: "Compartytion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <AppRouterCacheProvider>
          <CssVarsProvider theme={theme}>
            <AppBar>
              <Toolbar>
                <Typography variant={"h6"}>Compartytion</Typography>
              </Toolbar>
            </AppBar>
            <Toolbar />
            <main>{children}</main>
          </CssVarsProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
